site_name: Mesh Navigation Documentation
site_url: https://naturerobots.github.io/mesh_navigation_docs

repo_name: Github
repo_url: https://github.com/naturerobots/mesh_navigation

docs_dir: docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.copy
  logo: media/mesh_nav_icon_bg_white.png
  favicon: media/mesh_nav_icon.png
  palette:
    primary: blue

extra_css:
  - static/stylesheets/style.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - attr_list

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "100%"

validation:
  links:
    absolute_links: relative_to_docs

nav:
  - Home:
    - Overview: index.md
    - Installation: installation.md
    - Run: run.md
  - Theory:
    - Overview: theory/index.md
    - Why Meshes: theory/mesh_maps.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Quick-Start:
      - Overview: tutorials/index.md
      - Mesh Navigation: tutorials/mesh_navigation.md
      - Cost Layers: tutorials/mesh_cost_layers.md
      - Planner & Controller: tutorials/planner_and_controller.md
      - Virtual Worlds: tutorials/tutorial_worlds.md
    - Sim-To-Real:
      - Localization: tutorials/localization.md
      - Deliberation: tutorials/deliberation.md
    - Mesh Generation & Editing:
      - Mesh Mapping: tutorials/gen_edit/mesh_mapping.md
      - Flatten Surfaces: tutorials/gen_edit/flatten_surface.md
      - Align Mesh to Ground: tutorials/gen_edit/align_mesh_to_ground.md
      - Shrink Faces: tutorials/gen_edit/shrink_faces.md
    - Writing Plugins:
      - Own Cost Layer: tutorials/plugins/own_cost_layer.md
  - Library:
    - Overview: library/index.md
    - Cost Layer Plugin: library/cost_layer_plugin.md
    - Planner Plugin: library/planner_plugin.md
    - Controller Plugin: library/controller_plugin.md
  - Guides:
    - Overview: guides/index.md


